### ISSUE TITLE
Bug: recentForks can't be parsed by muesli/readme-scribe@master

### ISSUE THREAD

**Issue by jammutkarsh** [muesli/readme-scribe#14]
Description: I used the template provided in [markscribe](https://github.com/muesli/markscribe) built and ran it locally. [Locally](https://github.com/JammUtkarsh/jammutkarsh/tree/8af20f6463aa1bd7bfc6ace9c01d29f4c4740fea) it can parse `recentForks` but it fails on [GitHub Actions](https://github.com/JammUtkarsh/jammutkarsh/actions) saying
`Can't parse template: template: tpl:16: function "recentForks" not defined`

This issue can be faced when markscribe is installed using `brew install muesli/tap/markscribe` 

A possible suspect might be muesli/readme-scribe@master is not using the latest version of [markscribe](https://github.com/muesli/markscribe).

**Comment by muesli** [comment]
You're right and I still need to release a new version of markscribe that includes this functionality.

**Comment by glass-ships** [comment]
Potentially related, but `recentContributions` seems to have a similar issue preventing builds, despite working as expected with `markscribe` locally: 
> Can't render template: template: tpl:19:8: executing "tpl" at <recentContributions 5>: error calling recentContributions: non-200 OK status code: 401 Unauthorized body: "{\"message\":\"This endpoint requires you to be authenticated.\",\"documentation_url\":\"https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql\"}"


EDIT: 

Upon reading through some closed issues, I noticed this issue was effectively resolved by the proposed solution in #8 

Although it may be worth adding some documentation that it is required to set this secret in your repository's settings (as this is not universally true, and may not be obvious to some users)

**Comment by ok-coder1** [comment]
@muesli Are you updating `readme-scribe`?

I still get this:
```
Can't parse template: template: tpl:14: function "recentForks" not defined
```
